name: New Way to build Image

on:  
  push:    
    branches: [ master ]  

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Origin Repo
        uses: actions/checkout@v2
        with:
          repository: "miyouzi/aniGamerPlus"
          path: "aniGamerPlus"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          args: --target armv7-unknown-linux-gnueabihf
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sating/anigamerplus:armhf
          context: "aniGamerPlus"
          platforms: linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      
        
          
          
          
          
